spring.application.name=agro-notify
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/agro_notify
spring.datasource.username=postgres
spring.datasource.password=arthur15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false